import { MigrationInterface, QueryRunner } from "typeorm";

export class CompleteSchema1762165790637 implements MigrationInterface {
    name = 'CompleteSchema1762165790637'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."roles_tenanttype_enum" AS ENUM('ministere', 'crou', 'both')`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "description" character varying(255), "tenantType" "public"."roles_tenanttype_enum" NOT NULL DEFAULT 'crou', "isSystemRole" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(255), "updatedBy" character varying(255), CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'inactive', 'suspended', 'pending')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "password" character varying(255) NOT NULL, "name" character varying(255) NOT NULL, "first_name" character varying(100), "last_name" character varying(100), "is_active" boolean NOT NULL DEFAULT true, "role_id" uuid NOT NULL, "status" "public"."users_status_enum" NOT NULL DEFAULT 'active', "tenant_id" uuid NOT NULL, "phone" character varying(20), "avatar" character varying(255), "department" character varying(255), "lastLoginAt" TIMESTAMP, "lastLoginIp" inet, "loginAttempts" integer NOT NULL DEFAULT '0', "lockedUntil" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(255), "updatedBy" character varying(255), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tenants_type_enum" AS ENUM('ministere', 'crou')`);
        await queryRunner.query(`CREATE TABLE "tenants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "code" character varying(50) NOT NULL, "type" "public"."tenants_type_enum" NOT NULL, "region" character varying(255), "config" jsonb, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_32731f181236a46182a38c992a8" UNIQUE ("name"), CONSTRAINT "UQ_3021c18db2b363ae9324c826c5a" UNIQUE ("code"), CONSTRAINT "PK_53be67a04681c66b87ee27c9321" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."workflow_actions_type_enum" AS ENUM('approve', 'reject', 'delegate', 'escalate', 'skip', 'comment', 'assign', 'cancel', 'expire', 'start', 'complete')`);
        await queryRunner.query(`CREATE TYPE "public"."workflow_actions_status_enum" AS ENUM('pending', 'processing', 'completed', 'failed')`);
        await queryRunner.query(`CREATE TABLE "workflow_actions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "instance_id" uuid NOT NULL, "type" "public"."workflow_actions_type_enum" NOT NULL, "status" "public"."workflow_actions_status_enum" NOT NULL DEFAULT 'completed', "title" character varying(255) NOT NULL, "description" text, "comment" text, "data" jsonb, "metadata" jsonb, "userId" uuid NOT NULL, "userRole" character varying(255), "userName" character varying(255), "targetUserId" uuid, "targetUserRole" character varying(255), "targetUserName" character varying(255), "processedAt" TIMESTAMP, "errorMessage" character varying(500), "tenant_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_94d8dabade2a0ee1185e2753272" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_37b9fb2caf3ec3da8741f6b52a" ON "workflow_actions" ("userId", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_0e2e2be07e7b09d4623755bd46" ON "workflow_actions" ("instance_id", "type") `);
        await queryRunner.query(`CREATE INDEX "IDX_be494c9ee95644c35d83fec325" ON "workflow_actions" ("instance_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."workflow_instances_status_enum" AS ENUM('pending', 'in_progress', 'completed', 'rejected', 'cancelled', 'expired')`);
        await queryRunner.query(`CREATE TYPE "public"."workflow_instances_priority_enum" AS ENUM('low', 'medium', 'high', 'critical')`);
        await queryRunner.query(`CREATE TABLE "workflow_instances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workflow_id" uuid NOT NULL, "current_step_id" uuid, "entityType" character varying(100) NOT NULL, "entityId" uuid NOT NULL, "status" "public"."workflow_instances_status_enum" NOT NULL DEFAULT 'pending', "priority" "public"."workflow_instances_priority_enum" NOT NULL DEFAULT 'medium', "title" character varying(500), "description" text, "context" jsonb, "metadata" jsonb, "startedAt" TIMESTAMP, "completedAt" TIMESTAMP, "expiredAt" TIMESTAMP, "initiated_by" uuid NOT NULL, "assigned_to" uuid, "delegated_to" uuid, "rejectionReason" character varying(500), "cancellationReason" character varying(500), "tenant_id" uuid NOT NULL, "created_by" uuid NOT NULL, "updated_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_90cc94e44ff8b7b7869f50e4fc4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3c16e563acd66dd2bad1edfaee" ON "workflow_instances" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_2d784d6819c6daae037de2cfa4" ON "workflow_instances" ("entityType", "entityId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bffda5647dbdf3e67446f1e100" ON "workflow_instances" ("workflow_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_546667131c795ca3bf0e0d2393" ON "workflow_instances" ("tenant_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."workflows_module_enum" AS ENUM('financial', 'stocks', 'housing', 'transport', 'reports')`);
        await queryRunner.query(`CREATE TYPE "public"."workflows_type_enum" AS ENUM('sequential', 'parallel', 'conditional')`);
        await queryRunner.query(`CREATE TYPE "public"."workflows_status_enum" AS ENUM('draft', 'active', 'inactive', 'archived')`);
        await queryRunner.query(`CREATE TABLE "workflows" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" character varying(500), "module" "public"."workflows_module_enum" NOT NULL, "type" "public"."workflows_type_enum" NOT NULL DEFAULT 'sequential', "status" "public"."workflows_status_enum" NOT NULL DEFAULT 'draft', "entityType" character varying(100), "triggerEvent" character varying(100), "conditions" jsonb, "metadata" jsonb, "isActive" boolean NOT NULL DEFAULT true, "version" integer NOT NULL DEFAULT '0', "tenant_id" uuid NOT NULL, "created_by" uuid NOT NULL, "updated_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5b5757cc1cd86268019fef52e0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cacf348850bfae0cd173527233" ON "workflows" ("tenant_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_6392a0bf29001932e3bd68f802" ON "workflows" ("tenant_id", "module", "type") `);
        await queryRunner.query(`CREATE TYPE "public"."workflow_steps_type_enum" AS ENUM('approval', 'automatic', 'notification', 'condition')`);
        await queryRunner.query(`CREATE TYPE "public"."workflow_steps_priority_enum" AS ENUM('low', 'medium', 'high', 'critical')`);
        await queryRunner.query(`CREATE TYPE "public"."workflow_steps_status_enum" AS ENUM('pending', 'in_progress', 'completed', 'skipped', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "workflow_steps" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workflow_id" uuid NOT NULL, "name" character varying(255) NOT NULL, "description" character varying(500), "order" integer NOT NULL, "type" "public"."workflow_steps_type_enum" NOT NULL DEFAULT 'approval', "priority" "public"."workflow_steps_priority_enum" NOT NULL DEFAULT 'medium', "status" "public"."workflow_steps_status_enum" NOT NULL DEFAULT 'pending', "role" character varying(255), "permissions" jsonb, "conditions" jsonb, "actions" jsonb, "timeoutHours" integer, "isRequired" boolean NOT NULL DEFAULT false, "canSkip" boolean NOT NULL DEFAULT false, "canReject" boolean NOT NULL DEFAULT false, "canDelegate" boolean NOT NULL DEFAULT true, "metadata" jsonb, "isActive" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b602e5ecb22943db11c96a7f31c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a6c921863788830bbbdd8942f2" ON "workflow_steps" ("workflow_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_b6f91a8161ea3de7c9a9b23169" ON "workflow_steps" ("workflow_id", "order") `);
        await queryRunner.query(`CREATE TYPE "public"."vehicle_maintenances_type_enum" AS ENUM('preventive', 'corrective', 'revision', 'reparation')`);
        await queryRunner.query(`CREATE TYPE "public"."vehicle_maintenances_status_enum" AS ENUM('planned', 'in_progress', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "vehicle_maintenances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "vehicle_id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "title" character varying(255) NOT NULL, "description" text, "type" "public"."vehicle_maintenances_type_enum" NOT NULL, "status" "public"."vehicle_maintenances_status_enum" NOT NULL DEFAULT 'planned', "kilometrage" integer NOT NULL, "coutEstime" numeric(10,2), "coutReel" numeric(10,2), "devise" character varying(3) NOT NULL DEFAULT 'XOF', "dateDebut" date NOT NULL, "dateFin" date, "garage" character varying(255), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(255) NOT NULL, CONSTRAINT "PK_300f16840b4f0bd81303a594f79" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_09698b6feda02c49d425b87a1e" ON "vehicle_maintenances" ("tenant_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_3d87ac575e8bfea124fcf65b31" ON "vehicle_maintenances" ("vehicle_id", "type") `);
        await queryRunner.query(`CREATE TYPE "public"."vehicle_fuels_type_enum" AS ENUM('essence', 'diesel', 'gpl', 'electrique')`);
        await queryRunner.query(`CREATE TABLE "vehicle_fuels" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "vehicle_id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "type" "public"."vehicle_fuels_type_enum" NOT NULL, "quantite" numeric(8,2) NOT NULL, "prixUnitaire" numeric(10,2) NOT NULL, "montantTotal" numeric(15,2) NOT NULL, "devise" character varying(3) NOT NULL DEFAULT 'XOF', "station" character varying(255), "adresseStation" character varying(255), "kilometrage" integer NOT NULL, "date" date NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(255) NOT NULL, CONSTRAINT "PK_34fbee0e7f7c657f6555a5f5cf8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0e8afbdcefff384307480f11d6" ON "vehicle_fuels" ("tenant_id", "type") `);
        await queryRunner.query(`CREATE INDEX "IDX_96ff543eefe05254b0128814f9" ON "vehicle_fuels" ("vehicle_id", "date") `);
        await queryRunner.query(`CREATE TYPE "public"."vehicles_type_enum" AS ENUM('bus', 'minibus', 'utilitaire', 'voiture', 'moto', 'velo')`);
        await queryRunner.query(`CREATE TYPE "public"."vehicles_status_enum" AS ENUM('actif', 'hors_service', 'en_maintenance', 'en_panne', 'vendu', 'casse')`);
        await queryRunner.query(`CREATE TYPE "public"."vehicles_typecarburant_enum" AS ENUM('essence', 'diesel', 'gpl', 'electrique', 'hybride')`);
        await queryRunner.query(`CREATE TABLE "vehicles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "immatriculation" character varying(50) NOT NULL, "marque" character varying(100) NOT NULL, "modele" character varying(100) NOT NULL, "version" character varying(50), "type" "public"."vehicles_type_enum" NOT NULL, "status" "public"."vehicles_status_enum" NOT NULL DEFAULT 'actif', "annee" integer, "couleur" character varying(50), "numeroChassis" character varying(20), "numeroMoteur" character varying(20), "cylindree" integer, "puissance" integer, "typeCarburant" "public"."vehicles_typecarburant_enum", "capacitePassagers" integer, "capaciteCharge" numeric(8,2), "kilometrageActuel" integer NOT NULL DEFAULT '0', "kilometrageAchat" integer, "kilometrageMaintenance" integer, "kilometrageRevision" integer, "prixAchat" numeric(15,2), "valeurActuelle" numeric(15,2), "consommationMoyenne" numeric(8,2), "devise" character varying(3) NOT NULL DEFAULT 'XOF', "compagnieAssurance" character varying(100), "numeroAssurance" character varying(50), "dateExpirationAssurance" date, "dateExpirationControle" date, "dateExpirationVignette" date, "dateAchat" date, "dateMiseEnService" date, "dateDerniereMaintenance" date, "dateProchaineMaintenance" date, "isActif" boolean NOT NULL DEFAULT true, "maintenanceProgrammee" boolean NOT NULL DEFAULT false, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(255) NOT NULL, "updatedBy" character varying(255), CONSTRAINT "UQ_9b866ecdf13f76e6ba2ed87dafa" UNIQUE ("immatriculation"), CONSTRAINT "PK_18d8646b59304dce4af3a9e35b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9b866ecdf13f76e6ba2ed87daf" ON "vehicles" ("immatriculation") `);
        await queryRunner.query(`CREATE INDEX "IDX_41c7120cd99d750b006cd4f5ca" ON "vehicles" ("tenant_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_bbdbbef6e2820953815df95b92" ON "vehicles" ("tenant_id", "type") `);
        await queryRunner.query(`CREATE TYPE "public"."drivers_licensetype_enum" AS ENUM('A', 'B', 'C', 'D', 'E')`);
        await queryRunner.query(`CREATE TYPE "public"."drivers_status_enum" AS ENUM('active', 'inactive', 'suspended', 'on_leave', 'resigned')`);
        await queryRunner.query(`CREATE TABLE "drivers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "employeeId" character varying(50) NOT NULL, "firstName" character varying(100) NOT NULL, "lastName" character varying(100) NOT NULL, "email" character varying(150) NOT NULL, "phone" character varying(20) NOT NULL, "alternatePhone" character varying(20), "address" text, "dateOfBirth" date, "licenseNumber" character varying(50) NOT NULL, "licenseType" "public"."drivers_licensetype_enum" NOT NULL, "licenseIssueDate" date NOT NULL, "licenseExpiryDate" date NOT NULL, "licenseIssuingAuthority" character varying(100), "status" "public"."drivers_status_enum" NOT NULL DEFAULT 'active', "hireDate" date NOT NULL, "terminationDate" date, "position" character varying(100), "department" character varying(100), "assigned_vehicle_id" uuid, "yearsOfExperience" integer, "certifications" json, "specializations" text, "lastMedicalCheckup" date, "nextMedicalCheckup" date, "medicallyFit" boolean NOT NULL DEFAULT true, "totalTrips" integer NOT NULL DEFAULT '0', "totalKilometers" integer NOT NULL DEFAULT '0', "accidentCount" integer NOT NULL DEFAULT '0', "violationCount" integer NOT NULL DEFAULT '0', "performanceRating" numeric(3,2) NOT NULL DEFAULT '5', "isAvailable" boolean NOT NULL DEFAULT true, "currentStatus" character varying(50), "isActive" boolean NOT NULL DEFAULT true, "canDriveAtNight" boolean NOT NULL DEFAULT false, "canDriveLongDistance" boolean NOT NULL DEFAULT false, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(255) NOT NULL, "updatedBy" character varying(255), CONSTRAINT "UQ_b1ebdba4750ac5d230cb145979d" UNIQUE ("employeeId"), CONSTRAINT "UQ_d4cfc1aafe3a14622aee390edb2" UNIQUE ("email"), CONSTRAINT "UQ_754b3d50a8cc64f7ad5c24f62b4" UNIQUE ("licenseNumber"), CONSTRAINT "REL_288c0804c14303cfe6dcea6d9f" UNIQUE ("assigned_vehicle_id"), CONSTRAINT "PK_92ab3fb69e566d3eb0cae896047" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_754b3d50a8cc64f7ad5c24f62b" ON "drivers" ("licenseNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_b1ebdba4750ac5d230cb145979" ON "drivers" ("employeeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4fe4722424ed6dff65f53a2f26" ON "drivers" ("tenant_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."vehicle_usages_type_enum" AS ENUM('transport_etudiants', 'mission', 'maintenance', 'personnel')`);
        await queryRunner.query(`CREATE TABLE "vehicle_usages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "vehicle_id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "description" character varying(255) NOT NULL, "type" "public"."vehicle_usages_type_enum" NOT NULL, "kilometrageDebut" integer NOT NULL, "kilometrageFin" integer NOT NULL, "kilometrageParcouru" integer NOT NULL, "conducteur" character varying(255), "driver_id" uuid, "dateDebut" TIMESTAMP NOT NULL, "dateFin" TIMESTAMP NOT NULL, "date" date NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(255) NOT NULL, CONSTRAINT "PK_0b5828b224aaed53e84328db837" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_05609ee49b29b0ab4884fdcbad" ON "vehicle_usages" ("tenant_id", "type") `);
        await queryRunner.query(`CREATE INDEX "IDX_982d77d87c0b62b0ad2446c2e4" ON "vehicle_usages" ("vehicle_id", "date") `);
        await queryRunner.query(`CREATE TYPE "public"."transactions_type_enum" AS ENUM('depense', 'recette', 'engagement', 'ajustement', 'virement')`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_category_enum" AS ENUM('salaires', 'fournitures', 'maintenance', 'transport', 'communication', 'formation', 'equipement', 'travaux', 'loyers', 'tickets', 'subventions', 'autres')`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_status_enum" AS ENUM('draft', 'submitted', 'approved', 'rejected', 'executed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "budget_id" uuid NOT NULL, "budget_category_id" uuid, "libelle" character varying(255) NOT NULL, "description" text, "type" "public"."transactions_type_enum" NOT NULL, "category" "public"."transactions_category_enum" NOT NULL, "status" "public"."transactions_status_enum" NOT NULL DEFAULT 'draft', "montant" numeric(15,2) NOT NULL, "devise" character varying(3) NOT NULL DEFAULT 'XOF', "montantDevise" numeric(15,2), "tauxChange" numeric(8,4), "numeroPiece" character varying(255), "reference" character varying(255), "beneficiaire" character varying(255), "modePaiement" character varying(255), "date" date NOT NULL, "dateEcheance" date, "dateExecution" date, "validationLevel" integer NOT NULL DEFAULT '0', "nextValidator" character varying(255), "createdBy" character varying(255) NOT NULL, "approvedBy" character varying(255), "approvedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedBy" character varying(255), "created_by" uuid, CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_35fc4b83a39ef23f08a4b5ac9c" ON "transactions" ("type", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_19fc07b58120ad0a3873f93d6f" ON "transactions" ("budget_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_08f25099db1ca0dd6b9c0302dd" ON "transactions" ("tenant_id", "date") `);
        await queryRunner.query(`CREATE TYPE "public"."budget_categories_type_enum" AS ENUM('Personnel', 'Fonctionnement', 'Investissement', 'Subvention', 'Recette')`);
        await queryRunner.query(`CREATE TABLE "budget_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "budget_id" uuid NOT NULL, "libelle" character varying(255) NOT NULL, "description" text, "type" "public"."budget_categories_type_enum" NOT NULL, "code" character varying(10), "montantAlloue" numeric(15,2) NOT NULL, "montantRealise" numeric(15,2) NOT NULL DEFAULT '0', "montantEngage" numeric(15,2) NOT NULL DEFAULT '0', "montantDisponible" numeric(15,2) NOT NULL DEFAULT '0', "tauxExecution" numeric(5,2) NOT NULL DEFAULT '0', "pourcentageBudget" numeric(5,2) NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "ordre" integer NOT NULL DEFAULT '0', "seuilAlerte" numeric(5,2) NOT NULL DEFAULT '90', "enAlerte" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(255) NOT NULL, "updatedBy" character varying(255), CONSTRAINT "PK_2159c4d6372542f4629c4149045" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_585e8c1421c52710ee11df3770" ON "budget_categories" ("budget_id", "type") `);
        await queryRunner.query(`CREATE TYPE "public"."budget_trimesters_trimester_enum" AS ENUM('1', '2', '3', '4')`);
        await queryRunner.query(`CREATE TABLE "budget_trimesters" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "budget_id" uuid NOT NULL, "exercice" integer NOT NULL, "trimester" "public"."budget_trimesters_trimester_enum" NOT NULL, "libelle" character varying(50) NOT NULL, "montantAlloue" numeric(15,2) NOT NULL, "montantRealise" numeric(15,2) NOT NULL DEFAULT '0', "montantEngage" numeric(15,2) NOT NULL DEFAULT '0', "montantDisponible" numeric(15,2) NOT NULL DEFAULT '0', "tauxExecution" numeric(5,2) NOT NULL DEFAULT '0', "pourcentageBudget" numeric(5,2) NOT NULL DEFAULT '0', "dateDebut" date NOT NULL, "dateFin" date NOT NULL, "enAlerte" boolean NOT NULL DEFAULT false, "seuilAlerte" numeric(5,2) NOT NULL DEFAULT '90', "depasse" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(255) NOT NULL, "updatedBy" character varying(255), CONSTRAINT "PK_7c7da29c1d07f83ec52ada20bbd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d8ebf4eb6842d0da5807c91291" ON "budget_trimesters" ("budget_id", "exercice") `);
        await queryRunner.query(`CREATE INDEX "IDX_c2a03d39eddaf647a57edaf5cd" ON "budget_trimesters" ("budget_id", "trimester") `);
        await queryRunner.query(`CREATE TYPE "public"."budgets_type_enum" AS ENUM('national', 'crou', 'service')`);
        await queryRunner.query(`CREATE TYPE "public"."budgets_status_enum" AS ENUM('draft', 'submitted', 'approved', 'rejected', 'active', 'closed')`);
        await queryRunner.query(`CREATE TABLE "budgets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "exercice" integer NOT NULL, "type" "public"."budgets_type_enum" NOT NULL, "libelle" character varying(255) NOT NULL, "description" text, "montantInitial" numeric(15,2) NOT NULL, "montantRealise" numeric(15,2) NOT NULL DEFAULT '0', "montantEngage" numeric(15,2) NOT NULL DEFAULT '0', "montantDisponible" numeric(15,2) NOT NULL DEFAULT '0', "tauxExecution" numeric(5,2) NOT NULL DEFAULT '0', "status" "public"."budgets_status_enum" NOT NULL DEFAULT 'draft', "validationLevel" integer NOT NULL DEFAULT '0', "nextValidator" character varying(255), "createdBy" character varying(255) NOT NULL, "approvedBy" character varying(255), "approvedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedBy" character varying(255), CONSTRAINT "PK_9c8a51748f82387644b773da482" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_59bb8dad9ed33e7ed0c4730b90" ON "budgets" ("tenant_id", "type", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_7987a38ba979612b590896b997" ON "budgets" ("tenant_id", "exercice") `);
        await queryRunner.query(`CREATE TYPE "public"."validation_steps_entitytype_enum" AS ENUM('budget', 'transaction', 'purchase_order', 'contract')`);
        await queryRunner.query(`CREATE TYPE "public"."validation_steps_status_enum" AS ENUM('pending', 'approved', 'rejected', 'delegated', 'expired', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "validation_steps" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "entityType" "public"."validation_steps_entitytype_enum" NOT NULL, "entityId" character varying(255) NOT NULL, "budget_id" uuid, "transaction_id" uuid, "level" integer NOT NULL, "validatorId" character varying(255) NOT NULL, "status" "public"."validation_steps_status_enum" NOT NULL DEFAULT 'pending', "comment" text, "rejectionReason" text, "dueDate" TIMESTAMP NOT NULL, "completedAt" TIMESTAMP, "isEscalated" boolean NOT NULL DEFAULT false, "escalatedTo" character varying(255), "delegatedTo" character varying(255), "delegationReason" text, "createdBy" character varying(255) NOT NULL, "updatedBy" character varying(255), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "validator_id" uuid, CONSTRAINT "PK_f1ea110c47420d3f297738bf2fd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d69c9699994c9db0f176ceb790" ON "validation_steps" ("tenant_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_6eb628377648f9342276f0c3a0" ON "validation_steps" ("validatorId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_afebf4ab5fccfdcd01a06deeaa" ON "validation_steps" ("entityType", "entityId") `);
        await queryRunner.query(`CREATE TYPE "public"."scheduled_trips_status_enum" AS ENUM('scheduled', 'in_progress', 'completed', 'cancelled', 'delayed', 'no_show')`);
        await queryRunner.query(`CREATE TYPE "public"."scheduled_trips_cancellationreason_enum" AS ENUM('weather', 'vehicle_breakdown', 'driver_unavailable', 'low_demand', 'road_closed', 'other')`);
        await queryRunner.query(`CREATE TABLE "scheduled_trips" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "route_id" uuid NOT NULL, "vehicle_id" uuid, "driver_id" uuid, "vehicle_usage_id" uuid, "tripNumber" character varying(50) NOT NULL, "scheduledDate" date NOT NULL, "scheduledDepartureTime" TIME NOT NULL, "scheduledArrivalTime" TIME, "actualDepartureTime" TIMESTAMP, "actualArrivalTime" TIMESTAMP, "status" "public"."scheduled_trips_status_enum" NOT NULL DEFAULT 'scheduled', "passengersCount" integer NOT NULL DEFAULT '0', "seatsAvailable" integer, "reservationsCount" integer, "startKilometers" integer, "endKilometers" integer, "distanceCovered" numeric(8,2), "fuelCost" numeric(10,2), "tollCost" numeric(10,2), "otherCosts" numeric(10,2), "revenue" numeric(10,2), "delayMinutes" integer, "rating" numeric(3,2), "occupancyRate" numeric(5,2), "cancellationReason" "public"."scheduled_trips_cancellationreason_enum", "cancellationDetails" text, "cancelledAt" TIMESTAMP, "cancelledBy" character varying(255), "hasIncident" boolean NOT NULL DEFAULT false, "incidentDescription" text, "weatherCondition" character varying(50), "roadCondition" character varying(50), "isRecurring" boolean NOT NULL DEFAULT false, "recurringPattern" character varying(50), "notes" text, "driverNotes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(255) NOT NULL, "updatedBy" character varying(255), CONSTRAINT "UQ_f0ce208397b3bd91052c1369b81" UNIQUE ("tripNumber"), CONSTRAINT "PK_73b7accc36e32269fc6ba7c9cd1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_272d3661ec1d4a00d9d4f2b013" ON "scheduled_trips" ("driver_id", "scheduledDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_8097d34e68cba0052aeeb33151" ON "scheduled_trips" ("vehicle_id", "scheduledDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_defcd995491b6395474102c9a5" ON "scheduled_trips" ("route_id", "scheduledDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_0b50e6ea289572f2cc05e47325" ON "scheduled_trips" ("tenant_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_4f96c7e76644571e759ede6da3" ON "scheduled_trips" ("tenant_id", "scheduledDate") `);
        await queryRunner.query(`CREATE TYPE "public"."transport_routes_type_enum" AS ENUM('campus', 'inter_campus', 'city', 'intercity')`);
        await queryRunner.query(`CREATE TYPE "public"."transport_routes_status_enum" AS ENUM('active', 'inactive', 'maintenance', 'archived')`);
        await queryRunner.query(`CREATE TABLE "transport_routes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "code" character varying(20) NOT NULL, "name" character varying(200) NOT NULL, "description" text, "type" "public"."transport_routes_type_enum" NOT NULL DEFAULT 'city', "status" "public"."transport_routes_status_enum" NOT NULL DEFAULT 'active', "startLocation" character varying(200) NOT NULL, "endLocation" character varying(200) NOT NULL, "startLatitude" numeric(10,6), "startLongitude" numeric(10,6), "endLatitude" numeric(10,6), "endLongitude" numeric(10,6), "stops" json, "distance" numeric(8,2) NOT NULL, "estimatedDuration" integer NOT NULL, "roadCondition" character varying(50), "operatingDays" json, "startTime" character varying(10), "endTime" character varying(10), "frequencyMinutes" integer, "dailyTrips" integer, "maxPassengers" integer, "recommendedVehicleType" character varying(50), "fuelCostEstimate" numeric(10,2), "maintenanceCostEstimate" numeric(10,2), "ticketPrice" numeric(10,2), "totalTripsCompleted" integer NOT NULL DEFAULT '0', "totalPassengersTransported" integer NOT NULL DEFAULT '0', "averageOccupancyRate" numeric(10,2) NOT NULL DEFAULT '0', "rating" numeric(3,2) NOT NULL DEFAULT '5', "isActive" boolean NOT NULL DEFAULT true, "requiresReservation" boolean NOT NULL DEFAULT false, "isRoundTrip" boolean NOT NULL DEFAULT false, "priority" integer, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(255) NOT NULL, "updatedBy" character varying(255), CONSTRAINT "UQ_143c4dd81e5ca22f6779b32ff6d" UNIQUE ("code"), CONSTRAINT "PK_e4eb047cf1dd4133a5fe314ddf7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_143c4dd81e5ca22f6779b32ff6" ON "transport_routes" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_67db50cb667dc705f01ae2db3a" ON "transport_routes" ("tenant_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_69f64a3966dc988c8f026fc5d0" ON "transport_routes" ("tenant_id", "type") `);
        await queryRunner.query(`CREATE TYPE "public"."stock_movements_type_enum" AS ENUM('entree', 'sortie', 'ajustement', 'transfert', 'perte', 'retour')`);
        await queryRunner.query(`CREATE TYPE "public"."stock_movements_reason_enum" AS ENUM('reception', 'don', 'transfert_entree', 'inventaire_plus', 'distribution', 'vente', 'consommation', 'transfert_sortie', 'maintenance', 'inventaire_moins', 'perte', 'vol', 'perte_qualite', 'retour_fournisseur')`);
        await queryRunner.query(`CREATE TYPE "public"."stock_movements_status_enum" AS ENUM('draft', 'pending', 'confirmed', 'approved', 'rejected', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "stock_movements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "stock_id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "numero" character varying(100) NOT NULL, "libelle" character varying(255) NOT NULL, "description" text, "type" "public"."stock_movements_type_enum" NOT NULL, "reason" "public"."stock_movements_reason_enum" NOT NULL, "status" "public"."stock_movements_status_enum" NOT NULL DEFAULT 'draft', "quantite" numeric(10,3) NOT NULL, "quantiteAvant" numeric(10,3), "quantiteApres" numeric(10,3), "unit" character varying(20) NOT NULL, "prixUnitaire" numeric(10,2), "valeurTotale" numeric(15,2), "devise" character varying(3) NOT NULL DEFAULT 'XOF', "numeroBon" character varying(255), "numeroFacture" character varying(255), "fournisseur" character varying(255), "beneficiaire" character varying(255), "destinataire" character varying(255), "date" date NOT NULL, "dateConfirmation" TIMESTAMP, "createdBy" character varying(255) NOT NULL, "confirmedBy" character varying(255), "updatedBy" character varying(255), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "created_by" uuid, CONSTRAINT "PK_57a26b190618550d8e65fb860e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_39010d3219489450a67bbc9736" ON "stock_movements" ("date", "type") `);
        await queryRunner.query(`CREATE INDEX "IDX_c078dfff613df78f0bac2a9382" ON "stock_movements" ("tenant_id", "type") `);
        await queryRunner.query(`CREATE INDEX "IDX_f7d160246ab02c2da0b15ace6f" ON "stock_movements" ("stock_id", "date") `);
        await queryRunner.query(`CREATE TYPE "public"."stock_alerts_type_enum" AS ENUM('seuil_minimum', 'rupture', 'urgent', 'peremption', 'surstock', 'qualite')`);
        await queryRunner.query(`CREATE TYPE "public"."stock_alerts_priority_enum" AS ENUM('low', 'medium', 'high', 'critical')`);
        await queryRunner.query(`CREATE TYPE "public"."stock_alerts_status_enum" AS ENUM('active', 'acknowledged', 'resolved', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "stock_alerts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "stock_id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "type" "public"."stock_alerts_type_enum" NOT NULL, "priority" "public"."stock_alerts_priority_enum" NOT NULL, "status" "public"."stock_alerts_status_enum" NOT NULL DEFAULT 'active', "title" character varying(255) NOT NULL, "message" text NOT NULL, "description" text, "quantiteActuelle" numeric(10,3), "seuil" numeric(10,3), "joursRestants" integer, "actionRecommandee" text, "actionEffectuee" text, "resolvedBy" character varying(255), "resolvedAt" TIMESTAMP, "resolutionNote" text, "emailSent" boolean NOT NULL DEFAULT false, "smsSent" boolean NOT NULL DEFAULT false, "inAppSent" boolean NOT NULL DEFAULT false, "lastNotificationSent" TIMESTAMP, "escalated" boolean NOT NULL DEFAULT false, "escalatedTo" character varying(255), "escalatedAt" TIMESTAMP, "createdBy" character varying(255) NOT NULL, "updatedBy" character varying(255), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "created_by" uuid, CONSTRAINT "PK_3c3bb550b3bf192460bffe3a55b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_744a859dbe9b4bdb0e4bb691a8" ON "stock_alerts" ("priority", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_d9ab4a31f6473cc1aeea0f95af" ON "stock_alerts" ("tenant_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_bfbff01a5f6f1026c468f33c7c" ON "stock_alerts" ("stock_id", "type") `);
        await queryRunner.query(`CREATE TYPE "public"."stocks_type_enum" AS ENUM('centralise', 'local')`);
        await queryRunner.query(`CREATE TYPE "public"."stocks_category_enum" AS ENUM('cereales', 'denrees', 'fournitures', 'equipements', 'vehicules', 'maintenance')`);
        await queryRunner.query(`CREATE TYPE "public"."stocks_unit_enum" AS ENUM('kg', 'tonne', 'litre', 'unite', 'carton', 'sac', 'bouteille')`);
        await queryRunner.query(`CREATE TYPE "public"."stocks_status_enum" AS ENUM('actif', 'inactif', 'obsolete', 'en_rupture')`);
        await queryRunner.query(`CREATE TABLE "stocks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "code" character varying(100) NOT NULL, "libelle" character varying(255) NOT NULL, "description" text, "type" "public"."stocks_type_enum" NOT NULL, "category" "public"."stocks_category_enum" NOT NULL, "unit" "public"."stocks_unit_enum" NOT NULL, "status" "public"."stocks_status_enum" NOT NULL DEFAULT 'actif', "quantiteActuelle" numeric(10,3) NOT NULL DEFAULT '0', "quantiteReservee" numeric(10,3) NOT NULL DEFAULT '0', "quantiteDisponible" numeric(10,3) NOT NULL DEFAULT '0', "seuilMinimum" numeric(10,3) NOT NULL, "seuilMaximum" numeric(10,3), "quantiteCommande" numeric(10,3), "prixUnitaire" numeric(10,2), "valeurStock" numeric(15,2) NOT NULL DEFAULT '0', "devise" character varying(3) NOT NULL DEFAULT 'XOF', "supplier_id" uuid, "fournisseur" character varying(255), "referenceFournisseur" character varying(255), "dateDerniereEntree" date, "dateDerniereSortie" date, "datePeremption" date, "isPerissable" boolean NOT NULL DEFAULT true, "dureeConservation" integer, "isControle" boolean NOT NULL DEFAULT false, "isActif" boolean NOT NULL DEFAULT true, "enAlerte" boolean NOT NULL DEFAULT false, "enRupture" boolean NOT NULL DEFAULT false, "approvisionnementUrgent" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(255) NOT NULL, "updatedBy" character varying(255), CONSTRAINT "UQ_e66725c1ade202e47b78115e5cf" UNIQUE ("code"), CONSTRAINT "PK_b5b1ee4ac914767229337974575" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e66725c1ade202e47b78115e5c" ON "stocks" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_0fb0141cb55bd42cd269bef005" ON "stocks" ("tenant_id", "type", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_442f56bbc07c9f3235c1de84e7" ON "stocks" ("tenant_id", "category") `);
        await queryRunner.query(`CREATE TYPE "public"."suppliers_type_enum" AS ENUM('fournisseur', 'prestataire', 'fabricant', 'distributeur', 'grossiste', 'importateur')`);
        await queryRunner.query(`CREATE TYPE "public"."suppliers_status_enum" AS ENUM('actif', 'inactif', 'suspendu', 'bloque')`);
        await queryRunner.query(`CREATE TABLE "suppliers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "code" character varying(50) NOT NULL, "nom" character varying(255) NOT NULL, "nomCommercial" character varying(100), "type" "public"."suppliers_type_enum" NOT NULL, "status" "public"."suppliers_status_enum" NOT NULL DEFAULT 'actif', "description" text, "numeroSIRET" character varying(100), "numeroTVA" character varying(100), "registreCommerce" character varying(100), "adresse" text, "ville" character varying(100), "region" character varying(100), "pays" character varying(100), "codePostal" character varying(20), "email" character varying(255), "telephone" character varying(50), "fax" character varying(50), "siteWeb" character varying(255), "contactPrincipal" character varying(255), "emailContact" character varying(255), "telephoneContact" character varying(50), "fonctionContact" character varying(100), "iban" character varying(50), "bic" character varying(20), "banque" character varying(100), "delaiPaiement" integer NOT NULL DEFAULT '30', "devise" character varying(3) NOT NULL DEFAULT 'XOF', "categoriesProduits" jsonb, "produitsServices" text, "tauxRemise" numeric(5,2) DEFAULT '0', "montantMinCommande" numeric(15,2), "delaiLivraison" integer, "conditionsParticulieres" text, "noteQualite" numeric(3,2), "noteDelai" numeric(3,2), "notePrix" numeric(3,2), "noteMoyenne" numeric(3,2), "nombreCommandes" integer NOT NULL DEFAULT '0', "montantTotalCommandes" numeric(15,2) NOT NULL DEFAULT '0', "datePremiereCommande" date, "dateDerniereCommande" date, "isActif" boolean NOT NULL DEFAULT true, "isPreference" boolean NOT NULL DEFAULT false, "isCertifie" boolean NOT NULL DEFAULT false, "certifications" text, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(255) NOT NULL, "updatedBy" character varying(255), CONSTRAINT "UQ_6f01a03dcb1aa33822e19534cd6" UNIQUE ("code"), CONSTRAINT "PK_b70ac51766a9e3144f778cfe81e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_66181e465a65c2ddcfa9c00c9c" ON "suppliers" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_63ee8866be0464244c3c560c61" ON "suppliers" ("tenant_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ef177674b63d6bf4309b1df038" ON "suppliers" ("tenant_id", "code") `);
        await queryRunner.query(`CREATE TYPE "public"."housing_occupancies_status_enum" AS ENUM('active', 'terminated', 'suspended')`);
        await queryRunner.query(`CREATE TABLE "housing_occupancies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "housing_id" uuid NOT NULL, "room_id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "nom" character varying(255) NOT NULL, "prenom" character varying(255) NOT NULL, "email" character varying(255), "telephone" character varying(20), "numeroEtudiant" character varying(50), "universite" character varying(100), "filiere" character varying(100), "dateDebut" date NOT NULL, "dateFin" date, "status" "public"."housing_occupancies_status_enum" NOT NULL DEFAULT 'active', "loyerMensuel" numeric(10,2) NOT NULL, "caution" numeric(10,2), "devise" character varying(3) NOT NULL DEFAULT 'XOF', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(255) NOT NULL, CONSTRAINT "PK_7dfa0eca6688604340baa0aaf16" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_285606332233737728ebe23b47" ON "housing_occupancies" ("tenant_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_d4ea30ae0852661f72d1604f46" ON "housing_occupancies" ("housing_id", "room_id") `);
        await queryRunner.query(`CREATE TYPE "public"."housing_maintenances_type_enum" AS ENUM('preventive', 'corrective', 'urgente')`);
        await queryRunner.query(`CREATE TYPE "public"."housing_maintenances_status_enum" AS ENUM('planned', 'in_progress', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "housing_maintenances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "housing_id" uuid NOT NULL, "room_id" uuid, "tenant_id" uuid NOT NULL, "title" character varying(255) NOT NULL, "description" text, "type" "public"."housing_maintenances_type_enum" NOT NULL, "status" "public"."housing_maintenances_status_enum" NOT NULL DEFAULT 'planned', "coutEstime" numeric(10,2), "coutReel" numeric(10,2), "devise" character varying(3) NOT NULL DEFAULT 'XOF', "dateDebut" date NOT NULL, "dateFin" date, "prestataire" character varying(255), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(255) NOT NULL, CONSTRAINT "PK_483305204b69461ce4d2fce7a95" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7a12e443438d91287cd7673a68" ON "housing_maintenances" ("tenant_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_542c3d80bb35cc37a807347493" ON "housing_maintenances" ("housing_id", "type") `);
        await queryRunner.query(`CREATE TYPE "public"."housings_type_enum" AS ENUM('cite_universitaire', 'residence', 'foyer', 'logement_personnel')`);
        await queryRunner.query(`CREATE TYPE "public"."housings_category_enum" AS ENUM('standard', 'confort', 'luxe', 'handicape')`);
        await queryRunner.query(`CREATE TYPE "public"."housings_status_enum" AS ENUM('actif', 'inactif', 'en_construction', 'en_renovation', 'ferme')`);
        await queryRunner.query(`CREATE TABLE "housings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "code" character varying(100) NOT NULL, "nom" character varying(255) NOT NULL, "description" text, "type" "public"."housings_type_enum" NOT NULL, "category" "public"."housings_category_enum" NOT NULL, "status" "public"."housings_status_enum" NOT NULL DEFAULT 'actif', "adresse" character varying(255) NOT NULL, "ville" character varying(100), "region" character varying(100), "codePostal" character varying(20), "latitude" numeric(10,6), "longitude" numeric(10,6), "nombreChambres" integer NOT NULL, "capaciteTotale" integer NOT NULL, "occupationActuelle" integer NOT NULL DEFAULT '0', "tauxOccupation" numeric(5,2) NOT NULL DEFAULT '0', "loyerMensuel" numeric(10,2), "caution" numeric(10,2), "devise" character varying(3) NOT NULL DEFAULT 'XOF', "equipements" jsonb, "services" jsonb, "wifi" boolean NOT NULL DEFAULT false, "climatisation" boolean NOT NULL DEFAULT false, "chauffage" boolean NOT NULL DEFAULT false, "cuisine" boolean NOT NULL DEFAULT false, "laverie" boolean NOT NULL DEFAULT false, "parking" boolean NOT NULL DEFAULT false, "securite" boolean NOT NULL DEFAULT false, "dateConstruction" date, "dateRenovation" date, "dateOuverture" date, "dateFermeture" date, "isActif" boolean NOT NULL DEFAULT true, "maintenanceProgrammee" boolean NOT NULL DEFAULT false, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(255) NOT NULL, "updatedBy" character varying(255), CONSTRAINT "UQ_907f5dec7f11c07d9e1a9bcac1a" UNIQUE ("code"), CONSTRAINT "PK_891c9101818f0a1544930f0868d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_907f5dec7f11c07d9e1a9bcac1" ON "housings" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_b9d9cefc5a64dea814f89a59bd" ON "housings" ("tenant_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_b0aa996be782d7a0d5617ace10" ON "housings" ("tenant_id", "type") `);
        await queryRunner.query(`CREATE TYPE "public"."rooms_type_enum" AS ENUM('simple', 'double', 'triple', 'quadruple')`);
        await queryRunner.query(`CREATE TYPE "public"."rooms_status_enum" AS ENUM('disponible', 'occupe', 'maintenance', 'hors_service')`);
        await queryRunner.query(`CREATE TABLE "rooms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "housing_id" uuid NOT NULL, "numero" character varying(20) NOT NULL, "etage" character varying(50), "batiment" character varying(50), "type" "public"."rooms_type_enum" NOT NULL, "status" "public"."rooms_status_enum" NOT NULL DEFAULT 'disponible', "capacite" integer NOT NULL, "occupation" integer NOT NULL DEFAULT '0', "tauxOccupation" numeric(5,2) NOT NULL DEFAULT '0', "equipements" jsonb, "climatisation" boolean NOT NULL DEFAULT false, "chauffage" boolean NOT NULL DEFAULT false, "wifi" boolean NOT NULL DEFAULT false, "balcon" boolean NOT NULL DEFAULT false, "salleDeBain" boolean NOT NULL DEFAULT false, "cuisine" boolean NOT NULL DEFAULT false, "loyerMensuel" numeric(10,2), "caution" numeric(10,2), "devise" character varying(3) NOT NULL DEFAULT 'XOF', "dateDerniereMaintenance" date, "dateProchaineMaintenance" date, "isActif" boolean NOT NULL DEFAULT true, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(255) NOT NULL, "updatedBy" character varying(255), CONSTRAINT "PK_0368a2d7c215f2d0458a54933f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7f1f7e68e24044bff852850f51" ON "rooms" ("housing_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_183cffb9cb0d8aca59152901c9" ON "rooms" ("housing_id", "numero") `);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "resource" character varying(50) NOT NULL, "actions" json NOT NULL, "description" character varying(255), "conditions" json, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" character varying(255), "updatedBy" character varying(255), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "tokenHash" character varying(255) NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "isRevoked" boolean NOT NULL DEFAULT false, "revokedAt" TIMESTAMP, "revokedReason" character varying(255), "ipAddress" inet, "userAgent" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_56b91d98f71e3d1b649ed6e9f3" ON "refresh_tokens" ("expiresAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_ebaf21c40f2f6e6764c55a7343" ON "refresh_tokens" ("user_id", "isRevoked") `);
        await queryRunner.query(`CREATE TABLE "notification_preferences" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "channels" jsonb NOT NULL DEFAULT '{}', "categories" jsonb NOT NULL DEFAULT '{}', "types" jsonb NOT NULL DEFAULT '{}', "quietHours" jsonb, "frequency" jsonb NOT NULL DEFAULT '{}', "isEnabled" boolean NOT NULL DEFAULT true, "allowSounds" boolean NOT NULL DEFAULT true, "allowVibrations" boolean NOT NULL DEFAULT true, "language" character varying(10) NOT NULL DEFAULT 'fr', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_9c3e6cc717b4f6dc1b0260030f2" UNIQUE ("user_id", "tenant_id"), CONSTRAINT "PK_e94e2b543f2f218ee68e4f4fad2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e907e614e2cc6216ac076eb75e" ON "notification_preferences" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_64c90edc7310c6be7c10c96f67" ON "notification_preferences" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('info', 'success', 'warning', 'error', 'critical')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_category_enum" AS ENUM('financial', 'stocks', 'housing', 'transport', 'workflow', 'system', 'security')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_priority_enum" AS ENUM('low', 'medium', 'high', 'urgent', 'critical')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_status_enum" AS ENUM('pending', 'sent', 'delivered', 'read', 'failed')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_deliverymethods_enum" AS ENUM('in_app', 'email', 'sms', 'push', 'websocket', 'sse')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "user_id" uuid, "created_by" uuid NOT NULL, "title" character varying(255) NOT NULL, "message" text NOT NULL, "type" "public"."notifications_type_enum" NOT NULL DEFAULT 'info', "category" "public"."notifications_category_enum" NOT NULL, "priority" "public"."notifications_priority_enum" NOT NULL DEFAULT 'medium', "status" "public"."notifications_status_enum" NOT NULL DEFAULT 'pending', "role" character varying(100), "data" jsonb, "metadata" jsonb, "deliveryMethods" "public"."notifications_deliverymethods_enum" array NOT NULL DEFAULT '{in_app}', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "expires_at" TIMESTAMP, "read_at" TIMESTAMP, "delivered_at" TIMESTAMP, "isRead" boolean NOT NULL DEFAULT false, "isArchived" boolean NOT NULL DEFAULT false, "deliveryAttempts" integer NOT NULL DEFAULT '0', "deliveryError" text, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8c45eb3c00343786657b7edab2" ON "notifications" ("expires_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_77d2d971c58759c2e2249ce7d0" ON "notifications" ("status", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_400b108a9e02c5f33b5515c65e" ON "notifications" ("tenant_id", "category", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_634e0189576e45d657b6243f65" ON "notifications" ("tenant_id", "user_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('create', 'update', 'delete', 'login', 'login_failed', 'logout', 'view', 'read', 'export', 'validate', 'token_refresh', 'password_change', 'permission_denied', 'security_alert', 'custom', 'http_request', 'sensitive_operation', 'sensitive_operation_success', 'sensitive_operation_failed')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "action" "public"."audit_logs_action_enum" NOT NULL, "tableName" character varying(100) NOT NULL, "resource" character varying(100), "recordId" character varying(255), "resource_id" character varying(255), "success" boolean NOT NULL DEFAULT true, "oldValues" jsonb, "newValues" jsonb, "ipAddress" inet, "userAgent" text, "session_id" character varying(255), "tenant_id" uuid, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_109638590074998bb72a2f2cf08" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_actions" ADD CONSTRAINT "FK_d42c0357d91844bcfeb33677fbc" FOREIGN KEY ("instance_id") REFERENCES "workflow_instances"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_instances" ADD CONSTRAINT "FK_be0407ce5c835ef4240d78b9c1a" FOREIGN KEY ("workflow_id") REFERENCES "workflows"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_instances" ADD CONSTRAINT "FK_75bb18060c7c928f24c103a398f" FOREIGN KEY ("current_step_id") REFERENCES "workflow_steps"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflows" ADD CONSTRAINT "FK_04c65bd868207cfd3439ebcbab1" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workflow_steps" ADD CONSTRAINT "FK_02f0092e12343bfed27bb65fa89" FOREIGN KEY ("workflow_id") REFERENCES "workflows"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_maintenances" ADD CONSTRAINT "FK_480f5d890cf52ac1078f38635e6" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_maintenances" ADD CONSTRAINT "FK_1632c3b45e54a09217524725da6" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_fuels" ADD CONSTRAINT "FK_f11c77a67dd34cc223131e2acb6" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_fuels" ADD CONSTRAINT "FK_2863f84959851da7394024e4815" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD CONSTRAINT "FK_83421ac7781fdc9554f5256841d" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD CONSTRAINT "FK_7793872525aa2c0a99f86601d2b" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD CONSTRAINT "FK_288c0804c14303cfe6dcea6d9fe" FOREIGN KEY ("assigned_vehicle_id") REFERENCES "vehicles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_usages" ADD CONSTRAINT "FK_05227a7cb0de850535b0401ec8d" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_usages" ADD CONSTRAINT "FK_ecc87b199d042293b5e1cf70b21" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle_usages" ADD CONSTRAINT "FK_dd30df5f52e16f1602b891e5b53" FOREIGN KEY ("driver_id") REFERENCES "drivers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_4f27188c6c1d993bc76aeddcded" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_c9804d5c1ffeaad4795c32547a9" FOREIGN KEY ("budget_id") REFERENCES "budgets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_2a05a382b6536a930a1ef9b8423" FOREIGN KEY ("budget_category_id") REFERENCES "budget_categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_77e84561125adeccf287547f66e" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "budget_categories" ADD CONSTRAINT "FK_919faa73fd59efb0f80ccc36079" FOREIGN KEY ("budget_id") REFERENCES "budgets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "budget_trimesters" ADD CONSTRAINT "FK_b383a181b7b10607ba797a22cad" FOREIGN KEY ("budget_id") REFERENCES "budgets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "budgets" ADD CONSTRAINT "FK_9057940c4364457372df6b57eda" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "validation_steps" ADD CONSTRAINT "FK_b8bf4d5c6f2905e1bc445edd552" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "validation_steps" ADD CONSTRAINT "FK_c94feb7aac003cbd2d0780d25ce" FOREIGN KEY ("budget_id") REFERENCES "budgets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "validation_steps" ADD CONSTRAINT "FK_573df2f32c7487d365ebf856f64" FOREIGN KEY ("transaction_id") REFERENCES "transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "validation_steps" ADD CONSTRAINT "FK_cbbce6cf100c78cc9a8ca5300cf" FOREIGN KEY ("validator_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduled_trips" ADD CONSTRAINT "FK_1520492df23db1bc7608fedca89" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduled_trips" ADD CONSTRAINT "FK_624b7985baf1fe03d48894f0c44" FOREIGN KEY ("route_id") REFERENCES "transport_routes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduled_trips" ADD CONSTRAINT "FK_430e3da49ba5a8318ec062a8f64" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduled_trips" ADD CONSTRAINT "FK_0547c65e4c837741d62dce0b2e8" FOREIGN KEY ("driver_id") REFERENCES "drivers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduled_trips" ADD CONSTRAINT "FK_1f65da84b75dbb5323e0a7734a6" FOREIGN KEY ("vehicle_usage_id") REFERENCES "vehicle_usages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transport_routes" ADD CONSTRAINT "FK_3ead1929ed026d38c89617a12e5" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_fe1f8086b016f319c4f7f389602" FOREIGN KEY ("stock_id") REFERENCES "stocks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_30dd9acc22dcb6ae51d7d34f16d" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_0d3747894dc26f5f5c34f640d23" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" ADD CONSTRAINT "FK_a1b64ea6ad804f75c5edfe5f565" FOREIGN KEY ("stock_id") REFERENCES "stocks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" ADD CONSTRAINT "FK_cf66c3122681ce4c6bc90d7f881" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" ADD CONSTRAINT "FK_d43bc0642460bb8fe5082770201" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stocks" ADD CONSTRAINT "FK_04392e3d4bf16bde853ee35922e" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stocks" ADD CONSTRAINT "FK_d8e717f2132e2b6866a585905e2" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD CONSTRAINT "FK_b0d0350059126fa08fddc3c7a46" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "housing_occupancies" ADD CONSTRAINT "FK_89edfd627b4699aeb96b439c7ed" FOREIGN KEY ("housing_id") REFERENCES "housings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "housing_occupancies" ADD CONSTRAINT "FK_71915ebbfad416b1316a5d5d753" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "housing_occupancies" ADD CONSTRAINT "FK_5dbd2d521729d28757b8cbfca12" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "housing_maintenances" ADD CONSTRAINT "FK_0f12ed8126eac31e2d81ffbf7c3" FOREIGN KEY ("housing_id") REFERENCES "housings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "housing_maintenances" ADD CONSTRAINT "FK_2f2cf1c200df133f754e001a172" FOREIGN KEY ("room_id") REFERENCES "rooms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "housing_maintenances" ADD CONSTRAINT "FK_f410b9e95ef9bd07bba2e144994" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "housings" ADD CONSTRAINT "FK_3526a548313d9e6db3c222ffb63" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD CONSTRAINT "FK_83d50ac1c2bc54f5640f18fa702" FOREIGN KEY ("housing_id") REFERENCES "housings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" ADD CONSTRAINT "FK_64c90edc7310c6be7c10c96f675" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" ADD CONSTRAINT "FK_e907e614e2cc6216ac076eb75e5" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_d93ddd7e1b890535ecafbb334ec" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_19629e8eb1e6023c4c73e661c82" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_6f18d459490bb48923b1f40bdb7" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_6f18d459490bb48923b1f40bdb7"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_19629e8eb1e6023c4c73e661c82"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_d93ddd7e1b890535ecafbb334ec"`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" DROP CONSTRAINT "FK_e907e614e2cc6216ac076eb75e5"`);
        await queryRunner.query(`ALTER TABLE "notification_preferences" DROP CONSTRAINT "FK_64c90edc7310c6be7c10c96f675"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP CONSTRAINT "FK_83d50ac1c2bc54f5640f18fa702"`);
        await queryRunner.query(`ALTER TABLE "housings" DROP CONSTRAINT "FK_3526a548313d9e6db3c222ffb63"`);
        await queryRunner.query(`ALTER TABLE "housing_maintenances" DROP CONSTRAINT "FK_f410b9e95ef9bd07bba2e144994"`);
        await queryRunner.query(`ALTER TABLE "housing_maintenances" DROP CONSTRAINT "FK_2f2cf1c200df133f754e001a172"`);
        await queryRunner.query(`ALTER TABLE "housing_maintenances" DROP CONSTRAINT "FK_0f12ed8126eac31e2d81ffbf7c3"`);
        await queryRunner.query(`ALTER TABLE "housing_occupancies" DROP CONSTRAINT "FK_5dbd2d521729d28757b8cbfca12"`);
        await queryRunner.query(`ALTER TABLE "housing_occupancies" DROP CONSTRAINT "FK_71915ebbfad416b1316a5d5d753"`);
        await queryRunner.query(`ALTER TABLE "housing_occupancies" DROP CONSTRAINT "FK_89edfd627b4699aeb96b439c7ed"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP CONSTRAINT "FK_b0d0350059126fa08fddc3c7a46"`);
        await queryRunner.query(`ALTER TABLE "stocks" DROP CONSTRAINT "FK_d8e717f2132e2b6866a585905e2"`);
        await queryRunner.query(`ALTER TABLE "stocks" DROP CONSTRAINT "FK_04392e3d4bf16bde853ee35922e"`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" DROP CONSTRAINT "FK_d43bc0642460bb8fe5082770201"`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" DROP CONSTRAINT "FK_cf66c3122681ce4c6bc90d7f881"`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" DROP CONSTRAINT "FK_a1b64ea6ad804f75c5edfe5f565"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_0d3747894dc26f5f5c34f640d23"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_30dd9acc22dcb6ae51d7d34f16d"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_fe1f8086b016f319c4f7f389602"`);
        await queryRunner.query(`ALTER TABLE "transport_routes" DROP CONSTRAINT "FK_3ead1929ed026d38c89617a12e5"`);
        await queryRunner.query(`ALTER TABLE "scheduled_trips" DROP CONSTRAINT "FK_1f65da84b75dbb5323e0a7734a6"`);
        await queryRunner.query(`ALTER TABLE "scheduled_trips" DROP CONSTRAINT "FK_0547c65e4c837741d62dce0b2e8"`);
        await queryRunner.query(`ALTER TABLE "scheduled_trips" DROP CONSTRAINT "FK_430e3da49ba5a8318ec062a8f64"`);
        await queryRunner.query(`ALTER TABLE "scheduled_trips" DROP CONSTRAINT "FK_624b7985baf1fe03d48894f0c44"`);
        await queryRunner.query(`ALTER TABLE "scheduled_trips" DROP CONSTRAINT "FK_1520492df23db1bc7608fedca89"`);
        await queryRunner.query(`ALTER TABLE "validation_steps" DROP CONSTRAINT "FK_cbbce6cf100c78cc9a8ca5300cf"`);
        await queryRunner.query(`ALTER TABLE "validation_steps" DROP CONSTRAINT "FK_573df2f32c7487d365ebf856f64"`);
        await queryRunner.query(`ALTER TABLE "validation_steps" DROP CONSTRAINT "FK_c94feb7aac003cbd2d0780d25ce"`);
        await queryRunner.query(`ALTER TABLE "validation_steps" DROP CONSTRAINT "FK_b8bf4d5c6f2905e1bc445edd552"`);
        await queryRunner.query(`ALTER TABLE "budgets" DROP CONSTRAINT "FK_9057940c4364457372df6b57eda"`);
        await queryRunner.query(`ALTER TABLE "budget_trimesters" DROP CONSTRAINT "FK_b383a181b7b10607ba797a22cad"`);
        await queryRunner.query(`ALTER TABLE "budget_categories" DROP CONSTRAINT "FK_919faa73fd59efb0f80ccc36079"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_77e84561125adeccf287547f66e"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_2a05a382b6536a930a1ef9b8423"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_c9804d5c1ffeaad4795c32547a9"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_4f27188c6c1d993bc76aeddcded"`);
        await queryRunner.query(`ALTER TABLE "vehicle_usages" DROP CONSTRAINT "FK_dd30df5f52e16f1602b891e5b53"`);
        await queryRunner.query(`ALTER TABLE "vehicle_usages" DROP CONSTRAINT "FK_ecc87b199d042293b5e1cf70b21"`);
        await queryRunner.query(`ALTER TABLE "vehicle_usages" DROP CONSTRAINT "FK_05227a7cb0de850535b0401ec8d"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP CONSTRAINT "FK_288c0804c14303cfe6dcea6d9fe"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP CONSTRAINT "FK_7793872525aa2c0a99f86601d2b"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP CONSTRAINT "FK_83421ac7781fdc9554f5256841d"`);
        await queryRunner.query(`ALTER TABLE "vehicle_fuels" DROP CONSTRAINT "FK_2863f84959851da7394024e4815"`);
        await queryRunner.query(`ALTER TABLE "vehicle_fuels" DROP CONSTRAINT "FK_f11c77a67dd34cc223131e2acb6"`);
        await queryRunner.query(`ALTER TABLE "vehicle_maintenances" DROP CONSTRAINT "FK_1632c3b45e54a09217524725da6"`);
        await queryRunner.query(`ALTER TABLE "vehicle_maintenances" DROP CONSTRAINT "FK_480f5d890cf52ac1078f38635e6"`);
        await queryRunner.query(`ALTER TABLE "workflow_steps" DROP CONSTRAINT "FK_02f0092e12343bfed27bb65fa89"`);
        await queryRunner.query(`ALTER TABLE "workflows" DROP CONSTRAINT "FK_04c65bd868207cfd3439ebcbab1"`);
        await queryRunner.query(`ALTER TABLE "workflow_instances" DROP CONSTRAINT "FK_75bb18060c7c928f24c103a398f"`);
        await queryRunner.query(`ALTER TABLE "workflow_instances" DROP CONSTRAINT "FK_be0407ce5c835ef4240d78b9c1a"`);
        await queryRunner.query(`ALTER TABLE "workflow_actions" DROP CONSTRAINT "FK_d42c0357d91844bcfeb33677fbc"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_109638590074998bb72a2f2cf08"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_634e0189576e45d657b6243f65"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_400b108a9e02c5f33b5515c65e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77d2d971c58759c2e2249ce7d0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c45eb3c00343786657b7edab2"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_deliverymethods_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_64c90edc7310c6be7c10c96f67"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e907e614e2cc6216ac076eb75e"`);
        await queryRunner.query(`DROP TABLE "notification_preferences"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ebaf21c40f2f6e6764c55a7343"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_56b91d98f71e3d1b649ed6e9f3"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_183cffb9cb0d8aca59152901c9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f1f7e68e24044bff852850f51"`);
        await queryRunner.query(`DROP TABLE "rooms"`);
        await queryRunner.query(`DROP TYPE "public"."rooms_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."rooms_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b0aa996be782d7a0d5617ace10"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b9d9cefc5a64dea814f89a59bd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_907f5dec7f11c07d9e1a9bcac1"`);
        await queryRunner.query(`DROP TABLE "housings"`);
        await queryRunner.query(`DROP TYPE "public"."housings_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."housings_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."housings_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_542c3d80bb35cc37a807347493"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a12e443438d91287cd7673a68"`);
        await queryRunner.query(`DROP TABLE "housing_maintenances"`);
        await queryRunner.query(`DROP TYPE "public"."housing_maintenances_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."housing_maintenances_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d4ea30ae0852661f72d1604f46"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_285606332233737728ebe23b47"`);
        await queryRunner.query(`DROP TABLE "housing_occupancies"`);
        await queryRunner.query(`DROP TYPE "public"."housing_occupancies_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ef177674b63d6bf4309b1df038"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_63ee8866be0464244c3c560c61"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_66181e465a65c2ddcfa9c00c9c"`);
        await queryRunner.query(`DROP TABLE "suppliers"`);
        await queryRunner.query(`DROP TYPE "public"."suppliers_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."suppliers_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_442f56bbc07c9f3235c1de84e7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0fb0141cb55bd42cd269bef005"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e66725c1ade202e47b78115e5c"`);
        await queryRunner.query(`DROP TABLE "stocks"`);
        await queryRunner.query(`DROP TYPE "public"."stocks_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."stocks_unit_enum"`);
        await queryRunner.query(`DROP TYPE "public"."stocks_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."stocks_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bfbff01a5f6f1026c468f33c7c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d9ab4a31f6473cc1aeea0f95af"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_744a859dbe9b4bdb0e4bb691a8"`);
        await queryRunner.query(`DROP TABLE "stock_alerts"`);
        await queryRunner.query(`DROP TYPE "public"."stock_alerts_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."stock_alerts_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."stock_alerts_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7d160246ab02c2da0b15ace6f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c078dfff613df78f0bac2a9382"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_39010d3219489450a67bbc9736"`);
        await queryRunner.query(`DROP TABLE "stock_movements"`);
        await queryRunner.query(`DROP TYPE "public"."stock_movements_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."stock_movements_reason_enum"`);
        await queryRunner.query(`DROP TYPE "public"."stock_movements_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_69f64a3966dc988c8f026fc5d0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_67db50cb667dc705f01ae2db3a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_143c4dd81e5ca22f6779b32ff6"`);
        await queryRunner.query(`DROP TABLE "transport_routes"`);
        await queryRunner.query(`DROP TYPE "public"."transport_routes_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transport_routes_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4f96c7e76644571e759ede6da3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0b50e6ea289572f2cc05e47325"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_defcd995491b6395474102c9a5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8097d34e68cba0052aeeb33151"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_272d3661ec1d4a00d9d4f2b013"`);
        await queryRunner.query(`DROP TABLE "scheduled_trips"`);
        await queryRunner.query(`DROP TYPE "public"."scheduled_trips_cancellationreason_enum"`);
        await queryRunner.query(`DROP TYPE "public"."scheduled_trips_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_afebf4ab5fccfdcd01a06deeaa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6eb628377648f9342276f0c3a0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d69c9699994c9db0f176ceb790"`);
        await queryRunner.query(`DROP TABLE "validation_steps"`);
        await queryRunner.query(`DROP TYPE "public"."validation_steps_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."validation_steps_entitytype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7987a38ba979612b590896b997"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_59bb8dad9ed33e7ed0c4730b90"`);
        await queryRunner.query(`DROP TABLE "budgets"`);
        await queryRunner.query(`DROP TYPE "public"."budgets_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."budgets_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c2a03d39eddaf647a57edaf5cd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d8ebf4eb6842d0da5807c91291"`);
        await queryRunner.query(`DROP TABLE "budget_trimesters"`);
        await queryRunner.query(`DROP TYPE "public"."budget_trimesters_trimester_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_585e8c1421c52710ee11df3770"`);
        await queryRunner.query(`DROP TABLE "budget_categories"`);
        await queryRunner.query(`DROP TYPE "public"."budget_categories_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_08f25099db1ca0dd6b9c0302dd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19fc07b58120ad0a3873f93d6f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_35fc4b83a39ef23f08a4b5ac9c"`);
        await queryRunner.query(`DROP TABLE "transactions"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_982d77d87c0b62b0ad2446c2e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_05609ee49b29b0ab4884fdcbad"`);
        await queryRunner.query(`DROP TABLE "vehicle_usages"`);
        await queryRunner.query(`DROP TYPE "public"."vehicle_usages_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4fe4722424ed6dff65f53a2f26"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b1ebdba4750ac5d230cb145979"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_754b3d50a8cc64f7ad5c24f62b"`);
        await queryRunner.query(`DROP TABLE "drivers"`);
        await queryRunner.query(`DROP TYPE "public"."drivers_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."drivers_licensetype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bbdbbef6e2820953815df95b92"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_41c7120cd99d750b006cd4f5ca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9b866ecdf13f76e6ba2ed87daf"`);
        await queryRunner.query(`DROP TABLE "vehicles"`);
        await queryRunner.query(`DROP TYPE "public"."vehicles_typecarburant_enum"`);
        await queryRunner.query(`DROP TYPE "public"."vehicles_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."vehicles_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_96ff543eefe05254b0128814f9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0e8afbdcefff384307480f11d6"`);
        await queryRunner.query(`DROP TABLE "vehicle_fuels"`);
        await queryRunner.query(`DROP TYPE "public"."vehicle_fuels_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d87ac575e8bfea124fcf65b31"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_09698b6feda02c49d425b87a1e"`);
        await queryRunner.query(`DROP TABLE "vehicle_maintenances"`);
        await queryRunner.query(`DROP TYPE "public"."vehicle_maintenances_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."vehicle_maintenances_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b6f91a8161ea3de7c9a9b23169"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a6c921863788830bbbdd8942f2"`);
        await queryRunner.query(`DROP TABLE "workflow_steps"`);
        await queryRunner.query(`DROP TYPE "public"."workflow_steps_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."workflow_steps_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."workflow_steps_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6392a0bf29001932e3bd68f802"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cacf348850bfae0cd173527233"`);
        await queryRunner.query(`DROP TABLE "workflows"`);
        await queryRunner.query(`DROP TYPE "public"."workflows_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."workflows_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."workflows_module_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_546667131c795ca3bf0e0d2393"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bffda5647dbdf3e67446f1e100"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2d784d6819c6daae037de2cfa4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3c16e563acd66dd2bad1edfaee"`);
        await queryRunner.query(`DROP TABLE "workflow_instances"`);
        await queryRunner.query(`DROP TYPE "public"."workflow_instances_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."workflow_instances_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_be494c9ee95644c35d83fec325"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0e2e2be07e7b09d4623755bd46"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_37b9fb2caf3ec3da8741f6b52a"`);
        await queryRunner.query(`DROP TABLE "workflow_actions"`);
        await queryRunner.query(`DROP TYPE "public"."workflow_actions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."workflow_actions_type_enum"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
        await queryRunner.query(`DROP TYPE "public"."tenants_type_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TYPE "public"."roles_tenanttype_enum"`);
    }

}
